# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=22, verbose_name='phone number')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='address.Address')),
                ('delivery', models.ManyToManyField(related_name='delivery', to='address.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
