# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(max_length=15, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=22, null=True, verbose_name='phone number'),
        ),
    ]
