# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20170223_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('user_is_client', 'Check if user is  a client'),), 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
    ]
