# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20170224_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='address.Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='delivery',
            field=models.ManyToManyField(blank=True, null=True, related_name='delivery', to='address.Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='phone number'),
        ),
    ]
