# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20170530_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='delivery',
            field=models.ManyToManyField(blank=True, related_name='delivery', to='address.Address'),
        ),
    ]
