# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20170621_2322'),
        ('client', '0007_auto_20170609_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='delivery',
        ),
        migrations.AddField(
            model_name='client',
            name='delivery_address',
            field=models.ManyToManyField(blank=True, related_name='client', to='orders.DeliveryAddress'),
        ),
    ]
