# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20170622_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='consumer',
            field=models.BooleanField(default=True, verbose_name='consument'),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_liable',
            field=models.BooleanField(default=False, verbose_name='VAT liable'),
        ),
    ]
