# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20170719_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='consumer',
            field=models.BooleanField(default=True, verbose_name='end consumer'),
        ),
    ]
