# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20170609_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('archive_after', models.DurationField(verbose_name='archive after')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('start_time', models.TimeField(blank=True, verbose_name='start time')),
                ('end_date', models.DateField(blank=True, verbose_name='end date')),
                ('end_time', models.TimeField(blank=True, verbose_name='end time')),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='location')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_archivedevents', related_query_name='agenda_archivedevent', to='address.Address')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_archivedevents', related_query_name='agenda_archivedevent', to='agenda.Agenda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('start_time', models.TimeField(blank=True, verbose_name='start time')),
                ('end_date', models.DateField(blank=True, verbose_name='end date')),
                ('end_time', models.TimeField(blank=True, verbose_name='end time')),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='location')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_currentevents', related_query_name='agenda_currentevent', to='address.Address')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_currentevents', related_query_name='agenda_currentevent', to='agenda.Agenda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
