# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='archive_after',
            field=models.DurationField(choices=[(datetime.timedelta(1), '1 day'), (datetime.timedelta(7), '7 days'), (datetime.timedelta(31), '1 month')], verbose_name='archive after'),
        ),
        migrations.AlterField(
            model_name='archivedevent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='archivedevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='archivedevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='currentevent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='currentevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='currentevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
