# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20170612_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedevent',
            name='created_by',
            field=models.CharField(blank=True, max_length=80, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='currentevent',
            name='created_by',
            field=models.CharField(blank=True, max_length=80, verbose_name='created by'),
        ),
    ]
