# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20170720_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedevent',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_archivedevents', related_query_name='agenda_archivedevent', to='address.Address'),
        ),
        migrations.AlterField(
            model_name='currentevent',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_currentevents', related_query_name='agenda_currentevent', to='address.Address'),
        ),
    ]
