# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20170723_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedevent',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='currentevent',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
