# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20170726_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedevent',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_archivedevents', related_query_name='agenda_archivedevent', to='agenda.Agenda'),
        ),
        migrations.AlterField(
            model_name='currentevent',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_currentevents', related_query_name='agenda_currentevent', to='agenda.Agenda'),
        ),
    ]
