# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(help_text="You're name to refer to this address.", max_length=50, verbose_name='location name')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('name2', models.CharField(blank=True, max_length=120, verbose_name='name (2Nd line)')),
                ('street', models.CharField(max_length=80, verbose_name='street')),
                ('number', models.IntegerField(verbose_name='number')),
                ('bus', models.IntegerField(verbose_name='bus')),
                ('postal_code', models.CharField(max_length=15, verbose_name='postal code')),
                ('city', models.CharField(max_length=80, verbose_name='city')),
                ('province', models.CharField(max_length=80, verbose_name='province')),
                ('country', models.CharField(max_length=80, verbose_name='country')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
