# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='bus',
            field=models.CharField(blank=True, max_length=10, verbose_name='bus'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=80, verbose_name='province'),
        ),
    ]
