# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='online price')),
                ('vat_rate', models.DecimalField(decimal_places=2, help_text='percentage, e.g. 21', max_digits=6, verbose_name='VAR rate')),
            ],
        ),
    ]
