# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='listview_order',
            field=models.PositiveSmallIntegerField(default=100, help_text='Low numbers are shown first in the list views.', verbose_name='listview order'),
        ),
    ]
