# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_listview_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='listview_show',
            field=models.BooleanField(default=True, help_text='Set to false when article should not be displayed.', verbose_name='show in listview'),
        ),
    ]
