# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_listview_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='listview_show',
            field=models.BooleanField(default=True, help_text='Uncheck when article should not be displayed.', verbose_name='show in listview'),
        ),
    ]
