# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='kind',
            field=models.CharField(choices=[('FR', 'Free'), ('NO', 'None')], default='NO', max_length=20, verbose_name='type'),
        ),
    ]
