# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20170722_1838'),
        ('orders', '0010_auto_20170722_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_events',
            field=models.ManyToManyField(to='agenda.CurrentEvent'),
        ),
    ]
