# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20170723_1649'),
        ('orders', '0011_orderitem_price_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='keyword_events',
            field=models.ManyToManyField(related_name='OrderItemKeyword', to='agenda.CurrentEvent'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_events',
            field=models.ManyToManyField(related_name='OrderItemPrice', to='agenda.CurrentEvent'),
        ),
    ]
