# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_deliverydatefordeliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydatefordeliveryaddress',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_deliverydatefordeliveryaddresss', related_query_name='orders_deliverydatefordeliveryaddress', to='agenda.Agenda'),
        ),
    ]
