# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20170726_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydatefordeliveryaddress',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.DeliveryAddress', verbose_name='delivery address'),
        ),
    ]
