# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20170609_1526'),
        ('agenda', '0008_auto_20170726_1203'),
        ('orders', '0015_auto_20170726_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChangeOnDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='location')),
                ('created_by', models.CharField(blank=True, max_length=80, verbose_name='created by')),
                ('finished', models.BooleanField(default=False, verbose_name='finished')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('new_vat', models.DecimalField(blank=True, decimal_places=2, help_text='percentage, e.g. 21', max_digits=6, verbose_name='VAT rate')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_pricechangeondates', related_query_name='orders_pricechangeondate', to='address.Address')),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_pricechangeondates', related_query_name='orders_pricechangeondate', to='agenda.Agenda')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem', verbose_name='order item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
