# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_pricechangeondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricechangeondate',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricechangeondate',
            name='new_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='percentage, e.g. 21', max_digits=6, null=True, verbose_name='VAT rate'),
        ),
    ]
