# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20170731_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.Address'),
        ),
    ]
