# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='keyword_events',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_events',
        ),
    ]
