# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20170719_1330'),
        ('orders', '0022_auto_20170801_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returned', models.BooleanField(default=False, verbose_name='returned')),
                ('refunded', models.BooleanField(default=False, verbose_name='returned')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='order')),
            ],
        ),
    ]
