# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.SmallIntegerField(default=1, verbose_name='state'),
        ),
    ]
