# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20170802_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='payed'),
        ),
    ]
