# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_orderline_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='order_date_limit',
            field=models.DurationField(choices=[(datetime.timedelta(0), 'no restrictions'), (datetime.timedelta(1), '1 day'), (datetime.timedelta(2), '2 days')], default=datetime.timedelta(2), verbose_name='orders accepted until'),
        ),
    ]
