# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='unique name to identify the product', max_length=50, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='unique name to identify this ingredient', max_length=50, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('contents', models.SmallIntegerField(help_text='contents in milliliter', verbose_name='contents')),
                ('weight', models.SmallIntegerField(help_text='weight in grams', verbose_name='weight')),
                ('deposit', models.BooleanField(verbose_name='deposit')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(blank=True, verbose_name='value')),
                ('unit', models.CharField(blank=True, choices=[('P', 'piece'), ('g', 'grams'), ('mg', 'milligrams'), ('l', 'liter'), ('cl', 'centiliter'), ('ml', 'milliliter')], max_length=2, verbose_name='unit')),
            ],
        ),
        migrations.CreateModel(
            name='Recepy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name to identify this recepy', max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientLine',
            fields=[
                ('quantity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='food.Quantity')),
            ],
            bases=('food.quantity',),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='the_recepy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.Recepy'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.Ingredient'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.Packing'),
        ),
        migrations.AddField(
            model_name='recepy',
            name='ingredients',
            field=models.ManyToManyField(through='food.IngredientLine', to='food.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='recepy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.Recepy'),
        ),
    ]
