# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='amount',
            field=models.SmallIntegerField(default=0, help_text='amount of ingredient in product', verbose_name='amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='unit',
            field=models.CharField(choices=[('ml', 'milliliter'), ('g', 'grams'), ('P', 'piece')], default='g', max_length=2, verbose_name='unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.CharField(blank=True, choices=[('P', 'piece'), ('g', 'grams'), ('mg', 'milligrams'), ('l', 'liter'), ('cl', 'centiliter'), ('ml', 'milliliter'), ('ts', 'teaspoon'), ('tb', 'tablespoon')], max_length=2, verbose_name='unit'),
        ),
    ]
