# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='order',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_foodproduct', to='orders.OrderItem'),
        ),
    ]
