# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20170419_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='category',
            field=models.SmallIntegerField(choices=[('lunch', 1), ('dessert', 2)], default='0', verbose_name='category'),
        ),
    ]
