# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_foodproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'lunch'), (2, 'dessert')], default='0', verbose_name='category'),
        ),
    ]
