# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_foodproduct_website_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='website_detail_text',
            field=models.CharField(blank=True, help_text='Promo text on detail page', max_length=200, verbose_name='website detail text'),
        ),
    ]
