# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_foodproduct_website_detail_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientline',
            name='show_on_label',
            field=models.BooleanField(default=True, help_text='Show on printed labels', verbose_name='show on label'),
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='show_online',
            field=models.BooleanField(default=True, help_text='Show in online ingredient lists', verbose_name='show online'),
        ),
    ]
