# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20170425_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='food.Allergen'),
        ),
    ]
