# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20170427_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='website_plural_name',
            field=models.CharField(blank=True, help_text='plural name on web pages', max_length=50, verbose_name='plural name'),
        ),
    ]
