# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_foodproduct_website_plural_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='deposit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='deposit value'),
        ),
    ]
